language: java
before_script:
  - sudo apt-get install ant-optional
after_success:
  - bash <(curl -s https://codecov.io/bash)
jdk:
  - openjdk8
addons:
  sonarcloud:
    organization: "jmc1005"
    token:
      secure: "59a2459dc338bcf0d5ff3a68598953e0a73eb9af" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner
