language: java
before_script:
  - sudo apt-get install ant-optional
after_success:
  - bash <(curl -s https://codecov.io/bash)
jdk:
  - openjdk8
addons:
  sonarcloud:
    organization: "jmc1005"
    token:
      secure: "**************************" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
